#!/usr/bin/env bash

BUILD=$PWD/_build
OUTDIR=$BUILD/tests
mkdir -p $OUTDIR
EXPR_TEST=$BUILD/hsExprTest
cd $1

FAILED=""

function check() {
    local GOT=$1
    local TEST=$2
    if echo $TEST | grep -wqF $GOT; then
        echo "passed"
    else
        echo "failed (got $GOT)"
        echo "LOG: "
        cat $4
        echo "OUTPUT: "
        cat $3
        FAILED="$FAILED $TEST"
    fi
}

function runtest() {
    local FILE=$1
    local BASE=$(echo $FILE | sed 's/\.q.*$//')
    local INPUTS_=${BASE}*
    local INPUTS=$(echo $INPUTS_ | sed "s|$FILE||")

    for T in $INPUTS; do
        local OUT=$OUTDIR/$T.out
        local LOG=$OUTDIR/$T.log
        echo -n "${T}… "
        if $EXPR_TEST $FILE $T > $OUT 2> $LOG; then
            check "ok" $T $OUT $LOG
        else
            check "nok" $T $OUT $LOG
        fi
    done
}

while read F; do test -n "$F" && runtest $F; done <<< $(find -name '*.q*')

if test -n "$FAILED"; then
    echo "FAILED: $FAILED"
    exit 1
fi
