# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdlib, extensibleExceptions, hint, network, parsec
, QuickCheck, random
, hsExprTestSrc
}:

cabal.mkDerivation (self: {
  pname = "hsExprTest";
  version = "0.1.2";
  src = hsExprTestSrc;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    cmdlib extensibleExceptions hint network parsec QuickCheck random
  ];
  meta = {
    description = "Expression Testing";
    license = "BSD2";
    platforms = self.ghc.meta.platforms;
  };
})
