# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdlib, extensibleExceptions, hint, network, parsec
, QuickCheck, random
, hsExprTestSrc
, disable_shared ? false
}:

cabal.mkDerivation (self: {
  pname = "hsExprTest";
  version = "0.1.2";
  src = hsExprTestSrc;
  isLibrary = true;
  isExecutable = true;
  doCheck = false; # they can't pass without wrapper
  configureFlags = if disable_shared then "--disable-shared --disable-executable-dynamic" else "";
  buildDepends =  map (x: x.override {
      cabal = cabal.override { extension = self: super: { doCheck = false; }; };
  } )[
      cmdlib extensibleExceptions hint network parsec QuickCheck random
  ];
  meta = {
    description = "Expression Testing";
    license = "BSD2";
    platforms = self.ghc.meta.platforms;
  };
})
