# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Cabal, clock, cmdlib, deepseq, extensibleExceptions
, filepath, hint, network, parsec, QuickCheck, random, temporary
, transformers
, hsExprTestSrc
, disable_shared ? false
}:

cabal.mkDerivation (self: {
  pname = "hsExprTest";
  version = "0.1.99";
  src = hsExprTestSrc;
  isLibrary = true;
  isExecutable = true;
  doCheck = false; # they can't pass without wrapper
  configureFlags = if disable_shared then "--disable-shared --disable-executable-dynamic" else "";
  buildDepends =  map (x: x.override {
      cabal = cabal.override { extension = self: super: { doCheck = false; }; };
  } )[
      clock cmdlib deepseq extensibleExceptions filepath hint network
      parsec QuickCheck random temporary transformers
  ];
  meta = {
    description = "Expression Testing";
    license = "BSD2";
    platforms = self.ghc.meta.platforms;
  };
})
