#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Put in module header and remove possible UTF-8 BOM
cp Student.hs Submitted.hs

# GHC2021 default-enabled set of extensions (GHC 9.2+) enables some extensions
# that are not safe for use by students. So we disable them.
# On top of that, we enable Safe
EXTS="Safe, NoDeriveDataTypeable, NoDeriveFoldable, NoDeriveFunctor, NoDeriveGeneric, NoDeriveLift, NoDeriveTraversable, NoEmptyDataDeriving, NoGeneralizedNewtypeDeriving, NoStandaloneDeriving"
if [[ -f $DIR/_hs_extensions ]]; then
    EXTS="$EXTS, $(cat $DIR/_hs_extensions | tr -d '\n')"
fi

sed -i "1s/^\\(\\xEF\\xBB\\xBF\\)\\{0,1\\}/{-# LANGUAGE $EXTS #-}\n\nmodule Student where\n{-# LINE 1 \"Submitted.hs\" #-}\n/" Student.hs
WERRORS=(-Werror=missing-signatures)
# make sure student's file can be compiled with -XSafe before attemting to use
# its reflector
ghc -rtsopts -ieval -XSafe -c Student.hs ${WERRORS[@]} "$@"
perl $DIR/mkreflect.pl < Submitted.hs > StudentReflector.hs
ghc -rtsopts -ieval Main ${WERRORS[@]} "$@" -o hstest
