#!/usr/bin/env bash

START=$(date +%s)

global_timeout() {
    trap - ALRM
    echo "global_timeout triggered"
    pgrep -P $$
    pkill -9 -P $$
    pgrep -P $$
    pgrep hstest
    echo "post kill"
    last=$(tail -n1 out.list)
    if [[ "$last" ]]; then
        echo "FAILED: Global Timeout" >> out/$last
        last_test=$(tail -n1 test.journal)
        if [[ "$last_test" ]]; then
            echo "the last test might have been:" >> out/$last
            echo $last_test >> out/$last
        fi
    fi
    kill -ALRM $$
    exit 14
}

trap global_timeout ALRM

# drop sandboxing links for cc, sh, we don't use them and sh link can break GHC
BIN=$(readlink -f ../bin)
rm -f $BIN/*
ln -s $HOME/group $BIN
ln -s $HOME/sandbox $BIN
PATH=$(echo $PATH | sed "s|$HOME:||")

do_warnigns() {
    echo test.warnings >> out.list

    printf "Running warnings… "
    WARNINGS=(-Wmissing-signatures -Wunused-matches -Wincomplete-patterns -Widentities -Wredundant-constraints -Wunused-binds -Werror)
    rm *.hi *.o -f
    if ghc -ieval Main ${WARNINGS[@]} "$@" -o hstest_w  >& out/test.warnings; then
        echo "[passed]"
        touch passed/test.warnings
    else
        echo "[failed]"
    fi
}

do_lint() {
    local TEST=test.lint
    echo $TEST >> out.list
    printf "Running lint… "
    if ! which fi-hlint >&/dev/null; then
        echo "[missing]"
        return
    fi

    local LINT_OUT=out/$TEST
    fi-hlint Student.hs >& $LINT_OUT
    if [[ -s $LINT_OUT ]]; then
        # some warning exists
        echo "[failed]"
    else
        echo "[passed]"
        touch passed/$TEST
    fi
}

do_tests() {
    # actual tests
    export TEST_TIMEOUT=$(($FRAG_DEADLINE - $(date +%s)))
    # no sandbox here :-/
    ./hstest +RTS -M950M 2>> out/meta.errors & # async+wait for the sake of trap
    if wait $!; then
        touch passed/test
    fi
    if grep -q "Heap exhausted" out/meta.errors; then
        last=$(tail -n1 out.list)
        printf "\nOut of Memory\n" >> out/$last
    fi
}

touch out/meta.accept
echo meta.accept >> out.list
echo meta.errors >> out.list
echo test.compile >> out.list
printf "Running compilation… "
if ./eval/compile >& out/test.compile; then
    echo "[passed]"
    touch passed/test.compile
    touch passed/meta.accept

    # running in this order so that warnings are not skipped when timeout hits
    do_warnigns
    do_lint
    do_tests

    # move warnings & lint to the end
    sed '/^\(test.warnings\|test.lint\)$/d' -i out.list --follow-symlinks
    printf "test.warnings\ntest.lint" >> out.list
else
    echo "[failed]"
fi

echo "test.timing" >> out.list
touch passed/test.timing
echo "testsuite took $(($(date +%s) - $START))s, $(($FRAG_DEADLINE - $(date +%s)))s until deadline" > out/test.timing
